### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by TPL2008** [EricHedengren/StandardMaterials#2]
Quartz Tools
Glowstone (Maybe)
Blackstone tools
Granite, andesite, diorite and arenite
Redstone (With blocks)
Lapis

**Comment by TPL2008** [comment]
Sorry, im brazilian. In arenite, meant sandstone

**Comment by eric-hedengren** [comment]
These are great suggestions, but honestly, I'd like to keep the mod clean for people looking for obsidian and emerald equipment only. This potentially could be worked into a separate mod though, so I'll keep these in mind.
